# Generated by Django 2.1.7 on 2019-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20190325_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='nickname',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kaldenavn'),
        ),
    ]
