# Generated by Django 2.1.7 on 2019-03-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20190325_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='nickname',
        ),
    ]
